### ISSUE TITLE
ftp创建文件夹可能会出现问题，auto_run_on_remote/auto_run_on_remote/paramiko_util.py 的_make_dir当最后两级目录一样时可能会有问题。最后发现自己的问题，把/data/目录加入到配置文件auto_run_on_remote_config.py中的过滤了

### ISSUE THREAD

**Issue by DJMIN** [ydf0509/auto_run_on_remote#1]
@staticmethod
    def get_split_dir_path_list(path):
        res = [(path, '')]
        while True:
            root_path, final_dir = os.path.split(path)
            res.append((root_path, final_dir))
            path = root_path
            if root_path == "" or root_path == '/' or root_path.endswith(':\\'):
                break
        return res

    def make_dir_optimistic(self, path_dir):
        """
        乐观创建文件夹，假定所有父文件都已经被创建，此时效率高，能直接越级创建深层级文件夹。
        :return:
        """

        path_dir_l = self.get_split_dir_path_list(path_dir)
        need_make = []
        for root, folder in path_dir_l:
            try:
                self.ftp.mkd(root)
            except (ftplib.error_perm,) as ex:
                # print(root, str(ex))
                if str(ex) == '550 No such file or directory.':
                    need_make.insert(0, [root, folder])
                elif str(ex) == '550 File exists.':
                    break
                elif str(ex) == "550 Not a directory.":
                    raise OSError(f'创建{self}文件夹时出现同名文件：{root}') from None
                else:
                    raise OSError(f'创建{self}文件夹时出现问题：{root} {ex}')

        for root, folder in need_make:
            try:
                self.ftp.mkd(root)
            except (ftplib.error_perm,) as ex:
                # print(root, str(ex))
                raise OSError(f'创建{self}文件夹时出现问题：{root} {ex}')

    def make_dir_pessimistic(self, path_dir):
        """
        悲观创建文件夹，假定文件都没被创建，此时效率高，能直接越级创建深层级文件夹。
        :return:
        """
        path_dir_l = self.get_split_dir_path_list(path_dir)
        path_dir_l.reverse()
        need_make = []
        for root, folder in path_dir_l:
            try:
                self.ftp.mkd(root)
            except (ftplib.error_perm,) as ex:
                # print(root, str(ex))
                if str(ex) == "550 File exists.":
                    continue
                elif str(ex) == "550 Not a directory.":
                    raise OSError(f'创建{self}文件夹时出现同名文件：{root}') from None
                else:
                    raise OSError(f'创建{self}文件夹时出现问题：{root} {ex}')

        for root, folder in need_make:
            self.ftp.mkd(root)

**Comment by ydf0509** [comment]
真的吗，你试过？

**Comment by ydf0509** [comment]
为什么是可能有问题，到底是有还是没有

**Comment by DJMIN** [comment]
![image](https://user-images.githubusercontent.com/11349363/141888953-481d73d5-b367-4ef2-af00-5b9e215dbc3b.png)
![image](https://user-images.githubusercontent.com/11349363/141889033-5ac9b830-0c46-489a-ac22-62209d89590a.png)
![image](https://user-images.githubusercontent.com/11349363/141889067-c0999347-505a-48e5-9927-f91dacce5667.png)

**Comment by DJMIN** [comment]
看了下你的代码，这样写相对路径写代码是个大忌，有经验的人不会怎么写代码。  受到运行python命令行时候所处的文件夹路径影响。必须先切换到run1.py那个目录才能读取到，不信的话，沥青质在linux登录下试试就知道了。

**Comment by ydf0509** [comment]
我试试

> “可能”是因为我最近也刚好想弄一个你这个项目，研究了一下文件传输看了看你的代码实现，大脑里演绎了一下，感觉有问题，还没时间测试，今天测试了下确实有点问题，有且只有两级目录文件名相同时会出问题

**Comment by ydf0509** [comment]
> 好的我试试
> 
> > “可能”是因为我最近也刚好想弄一个你这个项目，研究了一下文件传输看了看你的代码实现，大脑里演绎了一下，感觉有问题，还没时间测试，今天测试了下确实有点问题，有且只有两级目录文件名相同时会出问题

**Comment by ydf0509** [comment]
from pathlib import Path
with  (Path(__file__).parent / Path('data/data/data')),   当前python文件的位置是__file__，这个永久固定的位置不会变，无论当前目录是什么，无论你在哪里启动run1.py


你上面那个写法，相对路径，你知道相对的是什么吗，是相对的当前目录，当前目录你以为是run1.py那个目录吗？你这么理解就是个错误。当前目录是用户运行 python xx.py命令行时候所处的文件夹。我项目执行命令时候永远是切换到项目根目录再运行python命令，而非是切换到当前python脚本所在的目录。只能说是你写的代码不靠谱，和我这个框架无关，你那样写非常的不稳固代码。

**Comment by ydf0509** [comment]
> from pathlib import Path with (Path(**file**).parent / Path('data/data/data')), 当前python文件的位置是__file__，这个永久固定的位置不会变，无论当前目录是什么，无论你在哪里启动run1.py
> 
> 你上面那个写法，相对路径，你知道相对的是什么吗，是相对的当前目录，当前目录你以为是run1.py那个目录吗？你这么理解就是个错误。当前目录是用户运行 python xx.py命令行时候所处的文件夹。我项目执行命令时候永远是切换到项目根目录再运行python命令，而非是切换到当前python脚本所在的目录。只能说是你写的代码不靠谱，和我这个框架无关，你那样写非常的不稳固代码。
用相对路径读取文件是大忌，python推荐以 __file__为原点去寻找定位其他文件的位置，这样无论你以什么脚本作为运行起点还是你运行代码时候所处的文件夹都不收影响。

**Comment by ydf0509** [comment]
你那个读取data的截个pycharm项目全文件夹截图看看，run1.py应该不在项目根目录，所以才会发生读取不到，你相对路径写代码有坑

**Comment by ydf0509** [comment]
例如 你a/b/c/d/e/run2.py 中import 那个run1读取data文件，你运行run2.py照样读去不到，因为相对路径你理解的是错误的，

**Comment by ydf0509** [comment]
![image](https://user-images.githubusercontent.com/26890690/141924933-bd21494d-f6f6-4fa2-a474-754ef254776c.png)
给你看看聪明人代码怎么写的，你那样的相对路径写代码真的很坑。写相对路径就不稳固不可靠，几乎没人你这么写。

**Comment by DJMIN** [comment]
Path这个库确实很不错，平时如果要正确读取文件我确实也会严格注意文件路径问题。
这里我代码中写了相对路径只是利用它快速测试文件是否存在，
我用其他 ssh工具登录到服务器上去查看也是文件没有被正确创建的状态。

本地文件夹整个是这样的，有两级data目录，最后有个data文件，程序文件处于项目根目录projectremote下
![image](https://user-images.githubusercontent.com/11349363/141927907-d0a3bc35-7d08-48c1-943e-f13b4d66a53b.png)

![image](https://user-images.githubusercontent.com/11349363/141926951-f8c551b1-5e3d-4884-a1ea-145ccbcf113b.png)
执行后，远程服务器文件是这样的
![image](https://user-images.githubusercontent.com/11349363/141927776-bc04fc82-58f0-4d15-8e29-05fa64d711c7.png)

**Comment by ydf0509** [comment]
我的上传成功了，你看文件内容都被读出来了，不然怎么读取的。

**Comment by ydf0509** [comment]
不是Path不错，最主要是你要理解使用  __file__  作为原点来定位到其他文件。这样的绝对路径非常稳固，但又不是写死全文见路径

双下划线file双下划线，   你要会使用啊，和用不用Path这个库没关系

**Comment by ydf0509** [comment]
![image](https://user-images.githubusercontent.com/26890690/141928476-0ecd837e-5f0a-4917-9b2b-0fb044c99877.png)
我已经上传正确了，你那个finalshell要刷新一下文件夹才会显示的。

**Comment by DJMIN** [comment]
data文件夹要处于PYTHON_PROJ_DIR_LOCAL路径的根目录

**Comment by DJMIN** [comment]
其实我们可以从函数出发分析，_make_dir递归调用的最后一次是比对前一次的文件夹的相对路径是否等于这一次的文件夹的相对路径那么我们只要构造这个情况出来就会发现问题

**Comment by ydf0509** [comment]
![image](https://user-images.githubusercontent.com/26890690/141930505-ea796d2d-7d6e-43dd-993b-648cdadab940.png)
 照样能够读取，我和你说的相对路径你到底听懂没。你现在读取文件的语法压根不靠谱，而不是没上传成功
![image](https://user-images.githubusercontent.com/26890690/141930665-889b95e8-3405-43d9-baa4-fb436f046f90.png)


先确定一点，用绝对路径读取data你能不能做到？

**Comment by ydf0509** [comment]
我把绝对路径的代码发你看看，现在不是没上传成功，而是你读取data压根不靠谱。

```
with (Path(__file__).parent / Path('data/data')).open('r', encoding='utf-8') as f:
    print(f.read())
```

**Comment by ydf0509** [comment]
你理解的相对，以为是相对于run1.py，真正的相对是指相对于你启动 python命令时候所处的文件夹，我不知道跟你强调了这么多相对路径和绝对路径，你到底能不能听懂。

**Comment by ydf0509** [comment]
你先把读取文件搞好了才能读取，不然上传也读取不到。

**Comment by DJMIN** [comment]
我说path包不错是因为我以前是这样取绝对路径：
![image](https://user-images.githubusercontent.com/11349363/141931765-a04d0d95-48e0-4d8a-9740-4cbf0e1005cd.png)
![image](https://user-images.githubusercontent.com/11349363/141931806-597e2a79-88ec-43ba-bbb9-66f0cc165b89.png)

好的，是的，以__file__为原点寻定位别的文件，用绝对路径比你相对路径好。现在win确认好用绝对路径代码没出错，再远程运行。

我刚刚是吧data放在项目根目录的，可以远程运行，也可以上传创建文件夹成功

**Comment by DJMIN** [comment]
run1.py和最外层data是同一级目录

**Comment by ydf0509** [comment]
![image](https://user-images.githubusercontent.com/26890690/141932356-e2704de9-a7b5-4fd9-ab56-224e4d22c15b.png)
![image](https://user-images.githubusercontent.com/26890690/141932419-eea7e002-1ec6-425d-9517-7c7eafe4e94b.png)
我把远程的data文件夹先删除了，run1.py放在项目根目录下，再运行也没有问题的。你不会是改了我的源代码再运行的吧

**Comment by DJMIN** [comment]
data目录下不能有其他文件

**Comment by DJMIN** [comment]
需要把data/run1.py删除再试试

**Comment by ydf0509** [comment]
> data目录下不能有其他文件

那你会不说我需要和你的项目名也要保持一样？

**Comment by ydf0509** [comment]
> 需要把data/run1.py删除再试试

是rm -rf ./data  ，删除了最外层的文件夹的。

**Comment by ydf0509** [comment]
> > 需要把data/run1.py删除再试试
> 
> 是rm -rf ./data ，删除了最外层的data文件夹的。

**Comment by ydf0509** [comment]
> > > 需要把data/run1.py删除再试试
> > 
> > 
> > 是rm -rf ./data ，删除了最外层的data文件夹的。确认是运行根目录下的run1.py的，你从控制台的print打印就能看到是ydfhome/run1.py 运行的脚本

**Comment by ydf0509** [comment]
你在pycahrm运行时候看下，这两个默认勾选的是不被你删除了？
![image](https://user-images.githubusercontent.com/26890690/141933379-9922ccb7-938e-4d5e-b7dc-35b69ef26e8a.png)

**Comment by DJMIN** [comment]
是需要本地的data/run1.py删除，因为如果data文件夹里有其他文件是会创建第一级data文件夹的这样就触发不了未创建data/data文件夹就直接上传data/data/data文件的异常了

**Comment by ydf0509** [comment]
> 是需要本地的data/run1.py删除，因为如果data文件夹里有其他文件是会创建第一级data文件夹的这样就触发不了未创建data/data文件夹就直接上传data/data/data文件的异常了

本地的删除了，远程的也删除了

![image](https://user-images.githubusercontent.com/26890690/141933918-74b79d13-4899-41ef-98ff-45434f861158.png)

![image](https://user-images.githubusercontent.com/26890690/141933834-6441cdb2-aede-4df6-8d8a-9b6960417240.png)

**Comment by ydf0509** [comment]
我每次执行run1.py前， 都在linux 执行了强制删除最外层data文件夹  rm -rf ./data。都能自动上传成功并读取

**Comment by ydf0509** [comment]
我早就想到越级创建文件夹的问题了，已近处理过了，没问题。

**Comment by ydf0509** [comment]
![image](https://user-images.githubusercontent.com/26890690/141934316-c99ac841-50ca-43af-89ea-7ba9344a8710.png)
  这就是打印的data文件的内容

**Comment by ydf0509** [comment]
加qq群 189603256 把你的文件夹打包发过来。

**Comment by DJMIN** [comment]
哦～那可能是系统不一致python解析路径也不同的问题了。我开发机也是linux然后配置了FORBID_DEPLOY_FROM_LINUX = False

**Comment by ydf0509** [comment]
![image](https://user-images.githubusercontent.com/26890690/141935202-b73bb552-27a2-4458-9c23-cf1f60b17e14.png)
把这个设置成DEBUG级别(10)    ，看看是不是出发了过滤？如果你设置只上传最近的1天修改过的或者data文件夹超过了容量限制，就会被过滤。不知道你有没有认证看过配置文件的介绍

**Comment by DJMIN** [comment]
最后发现是自己记性不好过滤了：/data/ 咚咚磕头
